services:
  postgres:
    ports: !reset []
  redis:
    ports: !reset []
  minio:
    ports: !reset []
  api:
    ports: !reset []
  ui:
    ports: !reset []
  nginx:
    ports: !override
      - "127.0.0.1:18443:443"
